use meta_signal_orchestrate::{AUTHORITY_INTERFACE_RUST, AUTHORITY_INTERFACE_SOURCE};

#[test]
fn authority_interface_is_role_free_and_strictly_generated() {
    assert!(
        AUTHORITY_INTERFACE_SOURCE.starts_with("Interface.{1 0 0}\n[]\n{\n  []\n  []\n  []\n  [")
    );
    assert!(AUTHORITY_INTERFACE_SOURCE.contains("LaneRegistrationMode.["));
    assert!(AUTHORITY_INTERFACE_SOURCE.contains("MetaOperationKind.["));
    assert!(AUTHORITY_INTERFACE_SOURCE.contains("RoleCreationRejectionReason.["));
    assert!(AUTHORITY_INTERFACE_RUST.starts_with(
        "// @generated by schema-rust from an authority-verified bootstrap Interface\n"
    ));
}

#[test]
fn build_uses_one_exact_verified_bootstrap_boundary() {
    let manifest = include_str!("../Cargo.toml");
    let build = include_str!("../build.rs");

    assert!(manifest.contains("9e36587c85bd69357e9042729ba2df0052799756"));
    assert!(manifest.contains("e9a53612df9bd80360768473202626b4fa3471ec"));
    assert_eq!(manifest.matches("schema-rust =").count(), 1);
    assert_eq!(build.matches("BootstrapInterfaceGeneration").count(), 2);
    assert!(build.contains("BootstrapTransactionAssembler"));
    assert!(build.contains("CargoEthosSourceMetadata"));
    assert!(build.contains("publish_owned_source_directory"));
}
