use meta_signal_orchestrate::{
    AUTHORITY_INTERFACE_RUST, AUTHORITY_INTERFACE_SOURCE, MetaOrchestrateWire,
};
use signal_frame::WireContract;

#[test]
fn authority_interface_is_refresh_only_and_strictly_generated() {
    assert_eq!(
        AUTHORITY_INTERFACE_SOURCE,
        "Interface.{1 0 0}\n[]\n{\n  []\n  []\n  []\n  [MetaOperationKind.[Refresh]]\n}\n"
    );
    assert_eq!(
        AUTHORITY_INTERFACE_RUST,
        "// @generated by schema-rust from an authority-verified bootstrap Interface\n\npub enum z2VMLA {z2VdQ2 ,} \n"
    );
}

#[test]
fn meta_wire_binding_advances_to_revision_two() {
    let binding = MetaOrchestrateWire::BINDING;
    assert_eq!(binding.contract().value(), 2);
    assert_eq!(binding.revision().value(), 2);
}
