// @generated by schema-rust from an authority-verified bootstrap Interface

pub enum z2VMLA {z2VUYE , z2VcPB , z2VcAg , z2VPtB , z2VTYS , z2Vcgy , z2VLDH , z2VdQ2 , z2VdVz , z2VXbg , z2Vd34 ,} 
pub enum z2VXhp {z2VMc1 , z2VQ69 ,} 
pub enum z2VPkA {z2VQB5 , z2VQD9 , z2VT8j ,} 
pub enum z2VRt6 {z2VQAc , z2VZgZ ,} 
pub enum z2VcbM {z2VQtj , z2Vc6Z ,} 
