//! The privileged Orchestrate wire contract, spoken on the meta socket.
//!
//! `ethos/signal.ethos` is the authored source and the only interface;
//! `src/generated/signal.rs` is its projection, regenerated by ethos-zero and
//! held byte-identical by `build.rs`. The contract's identity on the wire is
//! the digest of that source, settled once per connection by the greeting.

pub mod generated;
pub use generated::signal::*;

/// The authored Ethos source this contract is generated from, and the one
/// artefact its wire identity is computed over.
pub const ETHOS: &str = include_str!("../ethos/signal.ethos");

/// The querying side is the side that greets, so the identity is borne by
/// the query root.
impl signal::Contracted for Query {
    const CONTRACT_SOURCE: &'static str = ETHOS;
}
