// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_orchestrate::schema::lib::RoleIdentifier as RoleIdentifier;
#[rustfmt::skip]
pub use signal_orchestrate::schema::lib::Role as Role;
#[rustfmt::skip]
pub use signal_orchestrate::schema::lib::HarnessKind as HarnessKind;
#[rustfmt::skip]
pub use signal_orchestrate::schema::lib::LaneAuthority as LaneAuthority;
#[rustfmt::skip]
pub use signal_orchestrate::schema::lib::LaneIdentifier as LaneIdentifier;
#[rustfmt::skip]
pub use signal_orchestrate::schema::lib::LaneRegistration as LaneRegistration;
#[rustfmt::skip]
pub use signal_orchestrate::schema::lib::WirePath as WirePath;
#[rustfmt::skip]
pub use signal_orchestrate::schema::lib::Worktree as Worktree;
#[rustfmt::skip]
pub use signal_orchestrate::schema::lib::PartialApplied as PartialApplied;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CreateRoleOrder {
    pub role: RoleIdentifier,
    pub harness: HarnessKind,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetireRoleOrder(RoleIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Retirement {
    Role(RetireRoleOrder),
    Lane(LaneIdentifier),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RefreshRepositoryIndexOrder {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaneRegistrationRequest {
    pub role: Role,
    pub authority: LaneAuthority,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaneAuthorityChange {
    pub lane: LaneIdentifier,
    pub authority: LaneAuthority,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegisterWorktree(Worktree);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RefreshWorktreeIndexOrder {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleCreated {
    pub role: RoleIdentifier,
    pub harness: HarnessKind,
    pub report_repository_path: WirePath,
    pub report_lane_path: WirePath,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleRetired(RoleIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleCreationRejected {
    pub role: RoleIdentifier,
    pub reason: RoleCreationRejectionReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RoleCreationRejectionReason {
    RoleAlreadyExists,
    ReportRepositoryAlreadyExists,
    ReportLaneAlreadyExists,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RepositoryIndexRefreshed(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaneRegistered(LaneRegistration);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaneRetired(LaneIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaneAuthoritySet {
    pub lane: LaneIdentifier,
    pub authority: LaneAuthority,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WorktreeRegistered(Worktree);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WorktreeIndexRefreshed(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum MetaOperationKind {
    Create,
    Retire,
    Refresh,
    Register,
    SetAuthority,
    RegisterWorktree,
    RefreshWorktreeIndex,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum MetaOrchestrateUnimplementedReason {
    NotBuiltYet,
    DependencyNotReady,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MetaOrchestrateRequestUnimplemented {
    pub operation: MetaOperationKind,
    pub reason: MetaOrchestrateUnimplementedReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Create(CreateRoleOrder),
    Retire(Retirement),
    Refresh(RefreshRepositoryIndexOrder),
    Register(LaneRegistrationRequest),
    SetAuthority(LaneAuthorityChange),
    RegisterWorktree(RegisterWorktree),
    RefreshWorktreeIndex(RefreshWorktreeIndexOrder),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    RoleCreated(RoleCreated),
    RoleRetired(RoleRetired),
    RoleCreationRejected(RoleCreationRejected),
    RepositoryIndexRefreshed(RepositoryIndexRefreshed),
    LaneRegistered(LaneRegistered),
    LaneRetired(LaneRetired),
    LaneAuthoritySet(LaneAuthoritySet),
    WorktreeRegistered(WorktreeRegistered),
    WorktreeIndexRefreshed(WorktreeIndexRefreshed),
    PartialApplied(PartialApplied),
    MetaOrchestrateRequestUnimplemented(MetaOrchestrateRequestUnimplemented),
}

#[rustfmt::skip]
impl RetireRoleOrder {
    pub fn new(payload: RoleIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RoleIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> RoleIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<RoleIdentifier> for RetireRoleOrder {
    fn from(payload: RoleIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RegisterWorktree {
    pub fn new(payload: Worktree) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Worktree {
        &self.0
    }
    pub fn into_payload(self) -> Worktree {
        self.0
    }
}
#[rustfmt::skip]
impl From<Worktree> for RegisterWorktree {
    fn from(payload: Worktree) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RoleRetired {
    pub fn new(payload: RoleIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RoleIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> RoleIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<RoleIdentifier> for RoleRetired {
    fn from(payload: RoleIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RepositoryIndexRefreshed {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for RepositoryIndexRefreshed {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl LaneRegistered {
    pub fn new(payload: LaneRegistration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &LaneRegistration {
        &self.0
    }
    pub fn into_payload(self) -> LaneRegistration {
        self.0
    }
}
#[rustfmt::skip]
impl From<LaneRegistration> for LaneRegistered {
    fn from(payload: LaneRegistration) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl LaneRetired {
    pub fn new(payload: LaneIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &LaneIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> LaneIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<LaneIdentifier> for LaneRetired {
    fn from(payload: LaneIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WorktreeRegistered {
    pub fn new(payload: Worktree) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Worktree {
        &self.0
    }
    pub fn into_payload(self) -> Worktree {
        self.0
    }
}
#[rustfmt::skip]
impl From<Worktree> for WorktreeRegistered {
    fn from(payload: Worktree) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WorktreeIndexRefreshed {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for WorktreeIndexRefreshed {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Retirement {
    pub fn role(payload: RoleIdentifier) -> Self {
        Self::Role(RetireRoleOrder::new(payload))
    }
    pub fn lane(payload: LaneIdentifier) -> Self {
        Self::Lane(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn create(payload: CreateRoleOrder) -> Self {
        Self::Create(payload)
    }
    pub fn retire(payload: Retirement) -> Self {
        Self::Retire(payload)
    }
    pub fn refresh(payload: RefreshRepositoryIndexOrder) -> Self {
        Self::Refresh(payload)
    }
    pub fn register(payload: LaneRegistrationRequest) -> Self {
        Self::Register(payload)
    }
    pub fn set_authority(payload: LaneAuthorityChange) -> Self {
        Self::SetAuthority(payload)
    }
    pub fn register_worktree(payload: Worktree) -> Self {
        Self::RegisterWorktree(RegisterWorktree::new(payload))
    }
    pub fn refresh_worktree_index(payload: RefreshWorktreeIndexOrder) -> Self {
        Self::RefreshWorktreeIndex(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn role_created(payload: RoleCreated) -> Self {
        Self::RoleCreated(payload)
    }
    pub fn role_retired(payload: RoleIdentifier) -> Self {
        Self::RoleRetired(RoleRetired::new(payload))
    }
    pub fn role_creation_rejected(payload: RoleCreationRejected) -> Self {
        Self::RoleCreationRejected(payload)
    }
    pub fn repository_index_refreshed(payload: Integer) -> Self {
        Self::RepositoryIndexRefreshed(RepositoryIndexRefreshed::new(payload))
    }
    pub fn lane_registered(payload: LaneRegistration) -> Self {
        Self::LaneRegistered(LaneRegistered::new(payload))
    }
    pub fn lane_retired(payload: LaneIdentifier) -> Self {
        Self::LaneRetired(LaneRetired::new(payload))
    }
    pub fn lane_authority_set(payload: LaneAuthoritySet) -> Self {
        Self::LaneAuthoritySet(payload)
    }
    pub fn worktree_registered(payload: Worktree) -> Self {
        Self::WorktreeRegistered(WorktreeRegistered::new(payload))
    }
    pub fn worktree_index_refreshed(payload: Integer) -> Self {
        Self::WorktreeIndexRefreshed(WorktreeIndexRefreshed::new(payload))
    }
    pub fn partial_applied(payload: PartialApplied) -> Self {
        Self::PartialApplied(payload)
    }
    pub fn meta_orchestrate_request_unimplemented(
        payload: MetaOrchestrateRequestUnimplemented,
    ) -> Self {
        Self::MetaOrchestrateRequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
impl From<RetireRoleOrder> for Retirement {
    fn from(payload: RetireRoleOrder) -> Self {
        Self::Role(payload)
    }
}

#[rustfmt::skip]
impl From<LaneIdentifier> for Retirement {
    fn from(payload: LaneIdentifier) -> Self {
        Self::Lane(payload)
    }
}

#[rustfmt::skip]
impl From<CreateRoleOrder> for Input {
    fn from(payload: CreateRoleOrder) -> Self {
        Self::Create(payload)
    }
}

#[rustfmt::skip]
impl From<Retirement> for Input {
    fn from(payload: Retirement) -> Self {
        Self::Retire(payload)
    }
}

#[rustfmt::skip]
impl From<RefreshRepositoryIndexOrder> for Input {
    fn from(payload: RefreshRepositoryIndexOrder) -> Self {
        Self::Refresh(payload)
    }
}

#[rustfmt::skip]
impl From<LaneRegistrationRequest> for Input {
    fn from(payload: LaneRegistrationRequest) -> Self {
        Self::Register(payload)
    }
}

#[rustfmt::skip]
impl From<LaneAuthorityChange> for Input {
    fn from(payload: LaneAuthorityChange) -> Self {
        Self::SetAuthority(payload)
    }
}

#[rustfmt::skip]
impl From<RegisterWorktree> for Input {
    fn from(payload: RegisterWorktree) -> Self {
        Self::RegisterWorktree(payload)
    }
}

#[rustfmt::skip]
impl From<RefreshWorktreeIndexOrder> for Input {
    fn from(payload: RefreshWorktreeIndexOrder) -> Self {
        Self::RefreshWorktreeIndex(payload)
    }
}

#[rustfmt::skip]
impl From<RoleCreated> for Output {
    fn from(payload: RoleCreated) -> Self {
        Self::RoleCreated(payload)
    }
}

#[rustfmt::skip]
impl From<RoleRetired> for Output {
    fn from(payload: RoleRetired) -> Self {
        Self::RoleRetired(payload)
    }
}

#[rustfmt::skip]
impl From<RoleCreationRejected> for Output {
    fn from(payload: RoleCreationRejected) -> Self {
        Self::RoleCreationRejected(payload)
    }
}

#[rustfmt::skip]
impl From<RepositoryIndexRefreshed> for Output {
    fn from(payload: RepositoryIndexRefreshed) -> Self {
        Self::RepositoryIndexRefreshed(payload)
    }
}

#[rustfmt::skip]
impl From<LaneRegistered> for Output {
    fn from(payload: LaneRegistered) -> Self {
        Self::LaneRegistered(payload)
    }
}

#[rustfmt::skip]
impl From<LaneRetired> for Output {
    fn from(payload: LaneRetired) -> Self {
        Self::LaneRetired(payload)
    }
}

#[rustfmt::skip]
impl From<LaneAuthoritySet> for Output {
    fn from(payload: LaneAuthoritySet) -> Self {
        Self::LaneAuthoritySet(payload)
    }
}

#[rustfmt::skip]
impl From<WorktreeRegistered> for Output {
    fn from(payload: WorktreeRegistered) -> Self {
        Self::WorktreeRegistered(payload)
    }
}

#[rustfmt::skip]
impl From<WorktreeIndexRefreshed> for Output {
    fn from(payload: WorktreeIndexRefreshed) -> Self {
        Self::WorktreeIndexRefreshed(payload)
    }
}

#[rustfmt::skip]
impl From<PartialApplied> for Output {
    fn from(payload: PartialApplied) -> Self {
        Self::PartialApplied(payload)
    }
}

#[rustfmt::skip]
impl From<MetaOrchestrateRequestUnimplemented> for Output {
    fn from(payload: MetaOrchestrateRequestUnimplemented) -> Self {
        Self::MetaOrchestrateRequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_CREATE: u64 = 0x0000000000000000;
    pub const INPUT_RETIRE: u64 = 0x0001000000000000;
    pub const INPUT_REFRESH: u64 = 0x0002000000000000;
    pub const INPUT_REGISTER: u64 = 0x0003000000000000;
    pub const INPUT_SET_AUTHORITY: u64 = 0x0004000000000000;
    pub const INPUT_REGISTER_WORKTREE: u64 = 0x0005000000000000;
    pub const INPUT_REFRESH_WORKTREE_INDEX: u64 = 0x0006000000000000;
    pub const OUTPUT_ROLE_CREATED: u64 = 0x0100000000000000;
    pub const OUTPUT_ROLE_RETIRED: u64 = 0x0101000000000000;
    pub const OUTPUT_ROLE_CREATION_REJECTED: u64 = 0x0102000000000000;
    pub const OUTPUT_REPOSITORY_INDEX_REFRESHED: u64 = 0x0103000000000000;
    pub const OUTPUT_LANE_REGISTERED: u64 = 0x0104000000000000;
    pub const OUTPUT_LANE_RETIRED: u64 = 0x0105000000000000;
    pub const OUTPUT_LANE_AUTHORITY_SET: u64 = 0x0106000000000000;
    pub const OUTPUT_WORKTREE_REGISTERED: u64 = 0x0107000000000000;
    pub const OUTPUT_WORKTREE_INDEX_REFRESHED: u64 = 0x0108000000000000;
    pub const OUTPUT_PARTIAL_APPLIED: u64 = 0x0109000000000000;
    pub const OUTPUT_META_ORCHESTRATE_REQUEST_UNIMPLEMENTED: u64 = 0x010A000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Create,
    Retire,
    Refresh,
    Register,
    SetAuthority,
    RegisterWorktree,
    RefreshWorktreeIndex,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    RoleCreated,
    RoleRetired,
    RoleCreationRejected,
    RepositoryIndexRefreshed,
    LaneRegistered,
    LaneRetired,
    LaneAuthoritySet,
    WorktreeRegistered,
    WorktreeIndexRefreshed,
    PartialApplied,
    MetaOrchestrateRequestUnimplemented,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Create(_) => InputRoute::Create,
            Self::Retire(_) => InputRoute::Retire,
            Self::Refresh(_) => InputRoute::Refresh,
            Self::Register(_) => InputRoute::Register,
            Self::SetAuthority(_) => InputRoute::SetAuthority,
            Self::RegisterWorktree(_) => InputRoute::RegisterWorktree,
            Self::RefreshWorktreeIndex(_) => InputRoute::RefreshWorktreeIndex,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Create(_) => short_header::INPUT_CREATE,
            Self::Retire(_) => short_header::INPUT_RETIRE,
            Self::Refresh(_) => short_header::INPUT_REFRESH,
            Self::Register(_) => short_header::INPUT_REGISTER,
            Self::SetAuthority(_) => short_header::INPUT_SET_AUTHORITY,
            Self::RegisterWorktree(_) => short_header::INPUT_REGISTER_WORKTREE,
            Self::RefreshWorktreeIndex(_) => short_header::INPUT_REFRESH_WORKTREE_INDEX,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_CREATE => Ok(InputRoute::Create),
            short_header::INPUT_RETIRE => Ok(InputRoute::Retire),
            short_header::INPUT_REFRESH => Ok(InputRoute::Refresh),
            short_header::INPUT_REGISTER => Ok(InputRoute::Register),
            short_header::INPUT_SET_AUTHORITY => Ok(InputRoute::SetAuthority),
            short_header::INPUT_REGISTER_WORKTREE => Ok(InputRoute::RegisterWorktree),
            short_header::INPUT_REFRESH_WORKTREE_INDEX => {
                Ok(InputRoute::RefreshWorktreeIndex)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::RoleCreated(_) => OutputRoute::RoleCreated,
            Self::RoleRetired(_) => OutputRoute::RoleRetired,
            Self::RoleCreationRejected(_) => OutputRoute::RoleCreationRejected,
            Self::RepositoryIndexRefreshed(_) => OutputRoute::RepositoryIndexRefreshed,
            Self::LaneRegistered(_) => OutputRoute::LaneRegistered,
            Self::LaneRetired(_) => OutputRoute::LaneRetired,
            Self::LaneAuthoritySet(_) => OutputRoute::LaneAuthoritySet,
            Self::WorktreeRegistered(_) => OutputRoute::WorktreeRegistered,
            Self::WorktreeIndexRefreshed(_) => OutputRoute::WorktreeIndexRefreshed,
            Self::PartialApplied(_) => OutputRoute::PartialApplied,
            Self::MetaOrchestrateRequestUnimplemented(_) => {
                OutputRoute::MetaOrchestrateRequestUnimplemented
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::RoleCreated(_) => short_header::OUTPUT_ROLE_CREATED,
            Self::RoleRetired(_) => short_header::OUTPUT_ROLE_RETIRED,
            Self::RoleCreationRejected(_) => short_header::OUTPUT_ROLE_CREATION_REJECTED,
            Self::RepositoryIndexRefreshed(_) => {
                short_header::OUTPUT_REPOSITORY_INDEX_REFRESHED
            }
            Self::LaneRegistered(_) => short_header::OUTPUT_LANE_REGISTERED,
            Self::LaneRetired(_) => short_header::OUTPUT_LANE_RETIRED,
            Self::LaneAuthoritySet(_) => short_header::OUTPUT_LANE_AUTHORITY_SET,
            Self::WorktreeRegistered(_) => short_header::OUTPUT_WORKTREE_REGISTERED,
            Self::WorktreeIndexRefreshed(_) => {
                short_header::OUTPUT_WORKTREE_INDEX_REFRESHED
            }
            Self::PartialApplied(_) => short_header::OUTPUT_PARTIAL_APPLIED,
            Self::MetaOrchestrateRequestUnimplemented(_) => {
                short_header::OUTPUT_META_ORCHESTRATE_REQUEST_UNIMPLEMENTED
            }
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_ROLE_CREATED => Ok(OutputRoute::RoleCreated),
            short_header::OUTPUT_ROLE_RETIRED => Ok(OutputRoute::RoleRetired),
            short_header::OUTPUT_ROLE_CREATION_REJECTED => {
                Ok(OutputRoute::RoleCreationRejected)
            }
            short_header::OUTPUT_REPOSITORY_INDEX_REFRESHED => {
                Ok(OutputRoute::RepositoryIndexRefreshed)
            }
            short_header::OUTPUT_LANE_REGISTERED => Ok(OutputRoute::LaneRegistered),
            short_header::OUTPUT_LANE_RETIRED => Ok(OutputRoute::LaneRetired),
            short_header::OUTPUT_LANE_AUTHORITY_SET => Ok(OutputRoute::LaneAuthoritySet),
            short_header::OUTPUT_WORKTREE_REGISTERED => {
                Ok(OutputRoute::WorktreeRegistered)
            }
            short_header::OUTPUT_WORKTREE_INDEX_REFRESHED => {
                Ok(OutputRoute::WorktreeIndexRefreshed)
            }
            short_header::OUTPUT_PARTIAL_APPLIED => Ok(OutputRoute::PartialApplied),
            short_header::OUTPUT_META_ORCHESTRATE_REQUEST_UNIMPLEMENTED => {
                Ok(OutputRoute::MetaOrchestrateRequestUnimplemented)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "Create",
        "Retire",
        "Refresh",
        "Register",
        "SetAuthority",
        "RegisterWorktree",
        "RefreshWorktreeIndex",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
