// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

pub use signal_orchestrate::schema::lib::RoleIdentifier as RoleIdentifier;
pub use signal_orchestrate::schema::lib::Role as Role;
pub use signal_orchestrate::schema::lib::HarnessKind as HarnessKind;
pub use signal_orchestrate::schema::lib::LaneAuthority as LaneAuthority;
pub use signal_orchestrate::schema::lib::LaneIdentifier as LaneIdentifier;
pub use signal_orchestrate::schema::lib::LaneRegistration as LaneRegistration;
pub use signal_orchestrate::schema::lib::WirePath as WirePath;
pub use signal_orchestrate::schema::lib::PartialApplied as PartialApplied;

#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CreateRoleOrder {
    pub role: RoleIdentifier,
    pub harness: HarnessKind,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetireRoleOrder(pub RoleIdentifier);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Retirement {
    Role(RetireRoleOrder),
    Lane(LaneIdentifier),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RefreshRepositoryIndexOrder {}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaneRegistrationRequest {
    pub role: Role,
    pub authority: LaneAuthority,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaneAuthorityChange {
    pub lane: LaneIdentifier,
    pub authority: LaneAuthority,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleCreated {
    pub role: RoleIdentifier,
    pub harness: HarnessKind,
    pub report_repository_path: WirePath,
    pub report_lane_path: WirePath,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleRetired(pub RoleIdentifier);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleCreationRejected {
    pub role: RoleIdentifier,
    pub reason: RoleCreationRejectionReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RoleCreationRejectionReason {
    RoleAlreadyExists,
    ReportRepositoryAlreadyExists,
    ReportLaneAlreadyExists,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RepositoryIndexRefreshed(pub Integer);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaneRegistered(pub LaneRegistration);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaneRetired(pub LaneIdentifier);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaneAuthoritySet {
    pub lane: LaneIdentifier,
    pub authority: LaneAuthority,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum MetaOperationKind {
    Create,
    Retire,
    Refresh,
    Register,
    SetAuthority,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum MetaOrchestrateUnimplementedReason {
    NotBuiltYet,
    DependencyNotReady,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MetaOrchestrateRequestUnimplemented {
    pub operation: MetaOperationKind,
    pub reason: MetaOrchestrateUnimplementedReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Create(CreateRoleOrder),
    Retire(Retirement),
    Refresh(RefreshRepositoryIndexOrder),
    Register(LaneRegistrationRequest),
    SetAuthority(LaneAuthorityChange),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    RoleCreated(RoleCreated),
    RoleRetired(RoleRetired),
    RoleCreationRejected(RoleCreationRejected),
    RepositoryIndexRefreshed(RepositoryIndexRefreshed),
    LaneRegistered(LaneRegistered),
    LaneRetired(LaneRetired),
    LaneAuthoritySet(LaneAuthoritySet),
    PartialApplied(PartialApplied),
    MetaOrchestrateRequestUnimplemented(MetaOrchestrateRequestUnimplemented),
}

impl RetireRoleOrder {
    pub fn new(payload: RoleIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RoleIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> RoleIdentifier {
        self.0
    }
}
impl From<RoleIdentifier> for RetireRoleOrder {
    fn from(payload: RoleIdentifier) -> Self {
        Self::new(payload)
    }
}

impl RoleRetired {
    pub fn new(payload: RoleIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RoleIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> RoleIdentifier {
        self.0
    }
}
impl From<RoleIdentifier> for RoleRetired {
    fn from(payload: RoleIdentifier) -> Self {
        Self::new(payload)
    }
}

impl RepositoryIndexRefreshed {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
impl From<Integer> for RepositoryIndexRefreshed {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

impl LaneRegistered {
    pub fn new(payload: LaneRegistration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &LaneRegistration {
        &self.0
    }
    pub fn into_payload(self) -> LaneRegistration {
        self.0
    }
}
impl From<LaneRegistration> for LaneRegistered {
    fn from(payload: LaneRegistration) -> Self {
        Self::new(payload)
    }
}

impl LaneRetired {
    pub fn new(payload: LaneIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &LaneIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> LaneIdentifier {
        self.0
    }
}
impl From<LaneIdentifier> for LaneRetired {
    fn from(payload: LaneIdentifier) -> Self {
        Self::new(payload)
    }
}

impl Retirement {
    pub fn role(payload: RoleIdentifier) -> Self {
        Self::Role(RetireRoleOrder::new(payload))
    }
    pub fn lane(payload: LaneIdentifier) -> Self {
        Self::Lane(payload)
    }
}

impl Input {
    pub fn create(payload: CreateRoleOrder) -> Self {
        Self::Create(payload)
    }
    pub fn retire(payload: Retirement) -> Self {
        Self::Retire(payload)
    }
    pub fn refresh(payload: RefreshRepositoryIndexOrder) -> Self {
        Self::Refresh(payload)
    }
    pub fn register(payload: LaneRegistrationRequest) -> Self {
        Self::Register(payload)
    }
    pub fn set_authority(payload: LaneAuthorityChange) -> Self {
        Self::SetAuthority(payload)
    }
}

impl Output {
    pub fn role_created(payload: RoleCreated) -> Self {
        Self::RoleCreated(payload)
    }
    pub fn role_retired(payload: RoleIdentifier) -> Self {
        Self::RoleRetired(RoleRetired::new(payload))
    }
    pub fn role_creation_rejected(payload: RoleCreationRejected) -> Self {
        Self::RoleCreationRejected(payload)
    }
    pub fn repository_index_refreshed(payload: Integer) -> Self {
        Self::RepositoryIndexRefreshed(RepositoryIndexRefreshed::new(payload))
    }
    pub fn lane_registered(payload: LaneRegistration) -> Self {
        Self::LaneRegistered(LaneRegistered::new(payload))
    }
    pub fn lane_retired(payload: LaneIdentifier) -> Self {
        Self::LaneRetired(LaneRetired::new(payload))
    }
    pub fn lane_authority_set(payload: LaneAuthoritySet) -> Self {
        Self::LaneAuthoritySet(payload)
    }
    pub fn partial_applied(payload: PartialApplied) -> Self {
        Self::PartialApplied(payload)
    }
    pub fn meta_orchestrate_request_unimplemented(
        payload: MetaOrchestrateRequestUnimplemented,
    ) -> Self {
        Self::MetaOrchestrateRequestUnimplemented(payload)
    }
}

impl From<RetireRoleOrder> for Retirement {
    fn from(payload: RetireRoleOrder) -> Self {
        Self::Role(payload)
    }
}

impl From<LaneIdentifier> for Retirement {
    fn from(payload: LaneIdentifier) -> Self {
        Self::Lane(payload)
    }
}

impl From<CreateRoleOrder> for Input {
    fn from(payload: CreateRoleOrder) -> Self {
        Self::Create(payload)
    }
}

impl From<Retirement> for Input {
    fn from(payload: Retirement) -> Self {
        Self::Retire(payload)
    }
}

impl From<RefreshRepositoryIndexOrder> for Input {
    fn from(payload: RefreshRepositoryIndexOrder) -> Self {
        Self::Refresh(payload)
    }
}

impl From<LaneRegistrationRequest> for Input {
    fn from(payload: LaneRegistrationRequest) -> Self {
        Self::Register(payload)
    }
}

impl From<LaneAuthorityChange> for Input {
    fn from(payload: LaneAuthorityChange) -> Self {
        Self::SetAuthority(payload)
    }
}

impl From<RoleCreated> for Output {
    fn from(payload: RoleCreated) -> Self {
        Self::RoleCreated(payload)
    }
}

impl From<RoleRetired> for Output {
    fn from(payload: RoleRetired) -> Self {
        Self::RoleRetired(payload)
    }
}

impl From<RoleCreationRejected> for Output {
    fn from(payload: RoleCreationRejected) -> Self {
        Self::RoleCreationRejected(payload)
    }
}

impl From<RepositoryIndexRefreshed> for Output {
    fn from(payload: RepositoryIndexRefreshed) -> Self {
        Self::RepositoryIndexRefreshed(payload)
    }
}

impl From<LaneRegistered> for Output {
    fn from(payload: LaneRegistered) -> Self {
        Self::LaneRegistered(payload)
    }
}

impl From<LaneRetired> for Output {
    fn from(payload: LaneRetired) -> Self {
        Self::LaneRetired(payload)
    }
}

impl From<LaneAuthoritySet> for Output {
    fn from(payload: LaneAuthoritySet) -> Self {
        Self::LaneAuthoritySet(payload)
    }
}

impl From<PartialApplied> for Output {
    fn from(payload: PartialApplied) -> Self {
        Self::PartialApplied(payload)
    }
}

impl From<MetaOrchestrateRequestUnimplemented> for Output {
    fn from(payload: MetaOrchestrateRequestUnimplemented) -> Self {
        Self::MetaOrchestrateRequestUnimplemented(payload)
    }
}

#[cfg(feature = "nota-text")]
impl CreateRoleOrder {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RetireRoleOrder {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Retirement {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RefreshRepositoryIndexOrder {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl LaneRegistrationRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl LaneAuthorityChange {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RoleCreated {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RoleRetired {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RoleCreationRejected {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RoleCreationRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RepositoryIndexRefreshed {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl LaneRegistered {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl LaneRetired {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl LaneAuthoritySet {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl MetaOperationKind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl MetaOrchestrateUnimplementedReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl MetaOrchestrateRequestUnimplemented {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

pub mod short_header {
    pub const INPUT_CREATE: u64 = 0x0000000000000000;
    pub const INPUT_RETIRE: u64 = 0x0001000000000000;
    pub const INPUT_REFRESH: u64 = 0x0002000000000000;
    pub const INPUT_REGISTER: u64 = 0x0003000000000000;
    pub const INPUT_SET_AUTHORITY: u64 = 0x0004000000000000;
    pub const OUTPUT_ROLE_CREATED: u64 = 0x0100000000000000;
    pub const OUTPUT_ROLE_RETIRED: u64 = 0x0101000000000000;
    pub const OUTPUT_ROLE_CREATION_REJECTED: u64 = 0x0102000000000000;
    pub const OUTPUT_REPOSITORY_INDEX_REFRESHED: u64 = 0x0103000000000000;
    pub const OUTPUT_LANE_REGISTERED: u64 = 0x0104000000000000;
    pub const OUTPUT_LANE_RETIRED: u64 = 0x0105000000000000;
    pub const OUTPUT_LANE_AUTHORITY_SET: u64 = 0x0106000000000000;
    pub const OUTPUT_PARTIAL_APPLIED: u64 = 0x0107000000000000;
    pub const OUTPUT_META_ORCHESTRATE_REQUEST_UNIMPLEMENTED: u64 = 0x0108000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
impl std::error::Error for SignalFrameError {}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Create,
    Retire,
    Refresh,
    Register,
    SetAuthority,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    RoleCreated,
    RoleRetired,
    RoleCreationRejected,
    RepositoryIndexRefreshed,
    LaneRegistered,
    LaneRetired,
    LaneAuthoritySet,
    PartialApplied,
    MetaOrchestrateRequestUnimplemented,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Create(_) => InputRoute::Create,
            Self::Retire(_) => InputRoute::Retire,
            Self::Refresh(_) => InputRoute::Refresh,
            Self::Register(_) => InputRoute::Register,
            Self::SetAuthority(_) => InputRoute::SetAuthority,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Create(_) => short_header::INPUT_CREATE,
            Self::Retire(_) => short_header::INPUT_RETIRE,
            Self::Refresh(_) => short_header::INPUT_REFRESH,
            Self::Register(_) => short_header::INPUT_REGISTER,
            Self::SetAuthority(_) => short_header::INPUT_SET_AUTHORITY,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_CREATE => Ok(InputRoute::Create),
            short_header::INPUT_RETIRE => Ok(InputRoute::Retire),
            short_header::INPUT_REFRESH => Ok(InputRoute::Refresh),
            short_header::INPUT_REGISTER => Ok(InputRoute::Register),
            short_header::INPUT_SET_AUTHORITY => Ok(InputRoute::SetAuthority),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::RoleCreated(_) => OutputRoute::RoleCreated,
            Self::RoleRetired(_) => OutputRoute::RoleRetired,
            Self::RoleCreationRejected(_) => OutputRoute::RoleCreationRejected,
            Self::RepositoryIndexRefreshed(_) => OutputRoute::RepositoryIndexRefreshed,
            Self::LaneRegistered(_) => OutputRoute::LaneRegistered,
            Self::LaneRetired(_) => OutputRoute::LaneRetired,
            Self::LaneAuthoritySet(_) => OutputRoute::LaneAuthoritySet,
            Self::PartialApplied(_) => OutputRoute::PartialApplied,
            Self::MetaOrchestrateRequestUnimplemented(_) => {
                OutputRoute::MetaOrchestrateRequestUnimplemented
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::RoleCreated(_) => short_header::OUTPUT_ROLE_CREATED,
            Self::RoleRetired(_) => short_header::OUTPUT_ROLE_RETIRED,
            Self::RoleCreationRejected(_) => short_header::OUTPUT_ROLE_CREATION_REJECTED,
            Self::RepositoryIndexRefreshed(_) => {
                short_header::OUTPUT_REPOSITORY_INDEX_REFRESHED
            }
            Self::LaneRegistered(_) => short_header::OUTPUT_LANE_REGISTERED,
            Self::LaneRetired(_) => short_header::OUTPUT_LANE_RETIRED,
            Self::LaneAuthoritySet(_) => short_header::OUTPUT_LANE_AUTHORITY_SET,
            Self::PartialApplied(_) => short_header::OUTPUT_PARTIAL_APPLIED,
            Self::MetaOrchestrateRequestUnimplemented(_) => {
                short_header::OUTPUT_META_ORCHESTRATE_REQUEST_UNIMPLEMENTED
            }
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_ROLE_CREATED => Ok(OutputRoute::RoleCreated),
            short_header::OUTPUT_ROLE_RETIRED => Ok(OutputRoute::RoleRetired),
            short_header::OUTPUT_ROLE_CREATION_REJECTED => {
                Ok(OutputRoute::RoleCreationRejected)
            }
            short_header::OUTPUT_REPOSITORY_INDEX_REFRESHED => {
                Ok(OutputRoute::RepositoryIndexRefreshed)
            }
            short_header::OUTPUT_LANE_REGISTERED => Ok(OutputRoute::LaneRegistered),
            short_header::OUTPUT_LANE_RETIRED => Ok(OutputRoute::LaneRetired),
            short_header::OUTPUT_LANE_AUTHORITY_SET => Ok(OutputRoute::LaneAuthoritySet),
            short_header::OUTPUT_PARTIAL_APPLIED => Ok(OutputRoute::PartialApplied),
            short_header::OUTPUT_META_ORCHESTRATE_REQUEST_UNIMPLEMENTED => {
                Ok(OutputRoute::MetaOrchestrateRequestUnimplemented)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

